// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Blog
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL';
export const GET_BLOG_LIST_CATEGORIES_SUCCESS = 'GET_BLOG_LIST_CATEGORIES_SUCCESS';
export const GET_BLOG_LIST_CATEGORIES_FAIL = 'GET_BLOG_LIST_CATEGORIES_FAIL';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';

export const GET_BLOG_PAGINATION_RESULTS_SUCCESS = 'GET_BLOG_PAGINATION_RESULTS_SUCCESS';
export const GET_BLOG_PAGINATION_RESULTS_FAIL = 'GET_BLOG_PAGINATION_RESULTS_FAIL';

export const GET_SEARCH_BLOG_SUCCESS = 'GET_SEARCH_BLOG_SUCCESS';
export const GET_SEARCH_BLOG_FAIL = 'GET_SEARCH_BLOG_FAIL';

export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';
export const LOAD_PYTHONS_TOKEN_DATA_SUCCESS = 'LOAD_PYTHONS_TOKEN_DATA_SUCCESS';
export const LOAD_PYTHONS_TOKEN_DATA_FAIL = 'LOAD_PYTHONS_TOKEN_DATA_FAIL';
export const LOAD_PYTHONS_TOKEN_BALANCE_SUCCESS = 'LOAD_PYTHONS_TOKEN_BALANCE_SUCCESS';
export const LOAD_PYTHONS_TOKEN_BALANCE_FAIL = 'LOAD_PYTHONS_TOKEN_BALANCE_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOAD_NETWORK_SUCCESS = 'LOAD_NETWORK_SUCCESS';
export const LOAD_NETWORK_FAIL = 'LOAD_NETWORK_FAIL';
export const LOAD_GAS_SUCCESS = 'LOAD_GAS_SUCCESS';
export const LOAD_GAS_FAIL = 'LOAD_GAS_FAIL';


// Teacher Courses
export const GET_MY_COURSES_SUCCESS = 'GET_MY_COURSES_SUCCESS';
export const GET_MY_COURSES_FAIL = 'GET_MY_COURSES_FAIL';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const GET_COURSE_QUESTIONS_SUCCESS = 'GET_COURSE_QUESTIONS_SUCCESS';
export const GET_COURSE_QUESTIONS_FAIL = 'GET_COURSE_QUESTIONS_FAIL';
export const SEARCH_COURSES_SUCCESS = 'SEARCH_COURSES_SUCCESS';
export const SEARCH_COURSES_FAIL = 'SEARCH_COURSES_FAIL';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';
export const GET_COURSE_DATA_SUCCESS = 'GET_COURSE_DATA_SUCCESS';
export const GET_COURSE_DATA_FAIL = 'GET_COURSE_DATA_FAIL';
export const RELATED_COURSES_SUCCESS = 'RELATED_COURSES_SUCCESS';
export const RELATED_COURSES_FAIL = 'RELATED_COURSES_FAIL';
export const FILTER_COURSES_SUCCESS = 'FILTER_COURSES_SUCCESS';
export const FILTER_COURSES_FAIL = 'FILTER_COURSES_FAIL';
export const GET_COURSE_SECTION_SUCCESS = 'GET_COURSE_SECTION_SUCCESS';
export const GET_COURSE_SECTION_FAIL = 'GET_COURSE_SECTION_FAIL';
export const GET_RESOURCES_LIST_SUCCESS = 'GET_RESOURCES_LIST_SUCCESS';
export const GET_RESOURCES_LIST_FAIL = 'GET_RESOURCES_LIST_FAIL';
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
export const GET_EPISODE_FAIL = 'GET_EPISODE_FAIL';
export const GET_REQUISITES_SUCCESS = 'GET_REQUISITES_SUCCESS';
export const GET_REQUISITES_FAIL = 'GET_REQUISITES_FAIL';
export const GET_WHATLEARNT_SUCCESS = 'GET_WHATLEARNT_SUCCESS';
export const GET_WHATLEARNT_FAIL = 'GET_WHATLEARNT_FAIL';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';
export const GET_SECTIONS_FAIL = 'GET_SECTIONS_FAIL';
export const GET_PAID_SECTIONS_SUCCESS = 'GET_PAID_SECTIONS_SUCCESS';
export const GET_PAID_SECTIONS_FAIL = 'GET_PAID_SECTIONS_FAIL';
export const GET_COURSE_PRICES_SUCCESS = 'GET_COURSE_PRICES_SUCCESS';
export const GET_COURSE_PRICES_FAIL = 'GET_COURSE_PRICES_FAIL';
export const GET_COURSE_AUTHOR_SUCCESS = 'GET_COURSE_AUTHOR_SUCCESS';
export const GET_COURSE_AUTHOR_FAIL = 'GET_COURSE_AUTHOR_FAIL';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_FAIL = 'GET_COURSE_DETAILS_FAIL';
export const GET_USER_COURSES_SUCCESS = 'GET_USER_COURSES_SUCCESS';
export const GET_USER_COURSES_FAIL = 'GET_USER_COURSES_FAIL';
export const GET_COURSES_LIBRARY_SUCCESS = 'GET_COURSES_LIBRARY_SUCCESS';
export const GET_COURSES_LIBRARY_FAIL = 'GET_COURSES_LIBRARY_FAIL';
export const GET_COURSES_LIBRARY_PAGINATED_SUCCESS = 'GET_COURSES_LIBRARY_PAGINATED_SUCCESS';
export const GET_COURSES_LIBRARY_PAGINATED_FAIL = 'GET_COURSES_LIBRARY_PAGINATED_FAIL';
export const GET_PAID_COURSES_LIBRARY_SUCCESS = 'GET_PAID_COURSES_LIBRARY_SUCCESS';
export const GET_PAID_COURSES_LIBRARY_FAIL = 'GET_PAID_COURSES_LIBRARY_FAIL';
export const GET_PAID_COURSES_LIBRARY_PAGINATED_SUCCESS = 'GET_PAID_COURSES_LIBRARY_PAGINATED_SUCCESS';
export const GET_PAID_COURSES_LIBRARY_PAGINATED_FAIL = 'GET_PAID_COURSES_LIBRARY_PAGINATED_FAIL';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';
export const GET_COURSES_BY_ARRIVAL_SUCCESS = 'GET_COURSES_BY_ARRIVAL_SUCCESS';
export const GET_COURSES_BY_ARRIVAL_FAIL = 'GET_COURSES_BY_ARRIVAL_FAIL';
export const GET_COURSES_BY_SOLD_SUCCESS = 'GET_COURSES_BY_SOLD_SUCCESS';
export const GET_COURSES_BY_SOLD_FAIL = 'GET_COURSES_BY_SOLD_FAIL';
