// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Blog
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL';
export const GET_BLOG_LIST_CATEGORIES_SUCCESS = 'GET_BLOG_LIST_CATEGORIES_SUCCESS';
export const GET_BLOG_LIST_CATEGORIES_FAIL = 'GET_BLOG_LIST_CATEGORIES_FAIL';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';

export const GET_BLOG_PAGINATION_RESULTS_SUCCESS = 'GET_BLOG_PAGINATION_RESULTS_SUCCESS';
export const GET_BLOG_PAGINATION_RESULTS_FAIL = 'GET_BLOG_PAGINATION_RESULTS_FAIL';

export const GET_SEARCH_BLOG_SUCCESS = 'GET_SEARCH_BLOG_SUCCESS';
export const GET_SEARCH_BLOG_FAIL = 'GET_SEARCH_BLOG_FAIL';

export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';
export const LOAD_PYTHONS_TOKEN_DATA_SUCCESS = 'LOAD_PYTHONS_TOKEN_DATA_SUCCESS';
export const LOAD_PYTHONS_TOKEN_DATA_FAIL = 'LOAD_PYTHONS_TOKEN_DATA_FAIL';
export const LOAD_PYTHONS_TOKEN_BALANCE_SUCCESS = 'LOAD_PYTHONS_TOKEN_BALANCE_SUCCESS';
export const LOAD_PYTHONS_TOKEN_BALANCE_FAIL = 'LOAD_PYTHONS_TOKEN_BALANCE_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOAD_NETWORK_SUCCESS = 'LOAD_NETWORK_SUCCESS';
export const LOAD_NETWORK_FAIL = 'LOAD_NETWORK_FAIL';
export const LOAD_GAS_SUCCESS = 'LOAD_GAS_SUCCESS';
export const LOAD_GAS_FAIL = 'LOAD_GAS_FAIL';